name: islamic_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^16.3.2
  flutter_svg: ^2.0.10+1
  geolocator: ^11.0.0
  internet_connection_checker: ^1.0.0+1
  mqtt_client: ^10.2.0
  responsive_sizer: ^3.3.1
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/quran/
    - assets/quran/surahs/
    - assets/icons/
    - assets/icons/svg_icons/
    - assets/images/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/amiri/Amiri-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
